import gbloom
from datetime import datetime

k=20
bits=1100*8
filter = gbloom.Bloom(bits, k)

filter.add("Aardvark")
filter.add("Albatross")
filter.add("Alligator")
filter.add("Alpaca")
filter.add("Ant")
filter.add("Anteater")
filter.add("Antelope")
filter.add("Ape")
filter.add("Armadillo")
filter.add("Ass")
filter.add("Baboon")
filter.add("Badger")
filter.add("Barracuda")
filter.add("Bat")
filter.add("Bear")
filter.add("Beaver")
filter.add("Bee")
filter.add("Bison")
filter.add("Boar")
filter.add("Buffalo")
filter.add("Galago")
filter.add("Butterfly")
filter.add("Camel")
filter.add("Caribou")
filter.add("Cat")
filter.add("Caterpillar")
filter.add("Cattle")
filter.add("Chamois")
filter.add("Cheetah")
filter.add("Chicken")
filter.add("Chimpanzee")
filter.add("Chinchilla")
filter.add("Chough")
filter.add("Clam")
filter.add("Cobra")
filter.add("Cockroach")
filter.add("Cod")
filter.add("Cormorant")
filter.add("Coyote")
filter.add("Crab")
filter.add("Crane")
filter.add("Crocodile")
filter.add("Crow")
filter.add("Curlew")
filter.add("Deer")
filter.add("Dinosaur")
filter.add("Dog")
filter.add("Dogfish")
filter.add("Dolphin")
filter.add("Donkey")
filter.add("Dotterel")
filter.add("Dove")
filter.add("Dragonfly")
filter.add("Duck")
filter.add("Dugong")
filter.add("Dunlin")
filter.add("Eagle")
filter.add("Echidna")
filter.add("Eel")
filter.add("Eland")
filter.add("Elephant")
filter.add("Elephant seal")
filter.add("Elk")
filter.add("Emu")
filter.add("Falcon")
filter.add("Ferret")
filter.add("Finch")
filter.add("Fish")
filter.add("Flamingo")
filter.add("Fly")
filter.add("Fox")
filter.add("Frog")
filter.add("Gaur")
filter.add("Gazelle")
filter.add("Gerbil")
filter.add("Giant Panda")
filter.add("Giraffe")
filter.add("Gnat")
filter.add("Gnu")
filter.add("Goat")
filter.add("Goose")
filter.add("Goldfinch")
filter.add("Goldfish")
filter.add("Gorilla")
filter.add("Goshawk")
filter.add("Grasshopper")
filter.add("Grouse")
filter.add("Guanaco")
filter.add("Guinea fowl")
filter.add("Guinea pig")
filter.add("Gull")
filter.add("Hamster")
filter.add("Hare")
filter.add("Hawk")
filter.add("Hedgehog")
filter.add("Heron")
filter.add("Herring")
filter.add("Hippopotamus")
filter.add("Hornet")
filter.add("Horse")
filter.add("Human")
filter.add("Hummingbird")
filter.add("Hyena")
filter.add("Jackal")
filter.add("Jaguar")
filter.add("Jay")
filter.add("Jay, Blue")
filter.add("Jellyfish")
filter.add("Kangaroo")
filter.add("Koala")
filter.add("Komodo dragon")
filter.add("Kouprey")
filter.add("Kudu")
filter.add("Lapwing")
filter.add("Lark")
filter.add("Lemur")
filter.add("Leopard")
filter.add("Lion")
filter.add("Llama")
filter.add("Lobster")
filter.add("Locust")
filter.add("Loris")
filter.add("Louse")
filter.add("Lyrebird")
filter.add("Magpie")
filter.add("Mallard")
filter.add("Manatee")
filter.add("Marten")
filter.add("Meerkat")
filter.add("Mink")
filter.add("Mole")
filter.add("Monkey")
filter.add("Moose")
filter.add("Mouse")
filter.add("Mosquito")
filter.add("Mule")
filter.add("Narwhal")
filter.add("Newt")
filter.add("Nightingale")
filter.add("Octopus")
filter.add("Okapi")
filter.add("Opossum")
filter.add("Oryx")
filter.add("Ostrich")
filter.add("Otter")
filter.add("Owl")
filter.add("Ox")
filter.add("Oyster")
filter.add("Panther")
filter.add("Parrot")
filter.add("Partridge")
filter.add("Peafowl")
filter.add("Pelican")
filter.add("Penguin")
filter.add("Pheasant")
filter.add("Pig")
filter.add("Pigeon")
filter.add("Pony")
filter.add("Porcupine")
filter.add("Porpoise")
filter.add("Prairie Dog")
filter.add("Quail")
filter.add("Quelea")
filter.add("Rabbit")
filter.add("Raccoon")
filter.add("Rail")
filter.add("Ram")
filter.add("Rat")
filter.add("Raven")
filter.add("Red deer")
filter.add("Red panda")
filter.add("Reindeer")
filter.add("Rhinoceros")
filter.add("Rook")
filter.add("Ruff")
filter.add("Salamander")
filter.add("Salmon")
filter.add("Sand Dollar")
filter.add("Sandpiper")
filter.add("Sardine")
filter.add("Scorpion")
filter.add("Sea lion")
filter.add("Sea Urchin")
filter.add("Seahorse")
filter.add("Seal")
filter.add("Shark")
filter.add("Sheep")
filter.add("Shrew")
filter.add("Shrimp")
filter.add("Skunk")
filter.add("Snail")
filter.add("Snake")
filter.add("Spider")
filter.add("Squid")
filter.add("Squirrel")
filter.add("Starling")
filter.add("Stingray")
filter.add("Stinkbug")
filter.add("Stork")
filter.add("Swallow")
filter.add("Swan")
filter.add("Tapir")
filter.add("Tarsier")
filter.add("Termite")
filter.add("Tiger")
filter.add("Toad")
filter.add("Trout")
filter.add("Turkey")
filter.add("Turtle")
filter.add("Vicuna")
filter.add("Viper")
filter.add("Vulture")
filter.add("Wallaby")
filter.add("Walrus")
filter.add("Wasp")
filter.add("Water buffalo")
filter.add("Weasel")
filter.add("Whale")
filter.add("Wolf")
filter.add("Wolverine")
filter.add("Wombat")
filter.add("Woodcock")
filter.add("Woodpecker")
filter.add("Worm")
filter.add("Wren")
filter.add("Yak")
filter.add("Zebra")

print(filter.contains("Fish"))
print(filter.contains("Dog"))
print(filter.contains("Cat"))
print(filter.contains("at"))
print(filter.contains("fis"))
print(filter.contains("is"))
print(filter.contains("Donkey"))
print(filter.contains("Zebra"))

count = 170000
s = datetime.now()
for i in range(0, count):
    filter.contains("Fish")
    filter.contains("Donkey")
    filter.contains("Woodpecker")
    filter.contains("Salamander")
    filter.contains("Prairie")
    filter.contains("Rhinoceros")
    filter.contains("Porcupine")
    filter.contains("Hummingbird")
    filter.contains("Komodo dragon")
    filter.contains("Beaver")

td = datetime.now() - s
taken = float(td.seconds) + (float(td.microseconds) / 1000000)
print (taken)
print ("tested: {0}".format(count * 10))
